sdl example: SDL_GL_MULTISAMPLEBUFFERS=8 instead of 16:
8 is enough to get antialiasing, and on two of my machines (Ubuntu 20.04- docker, and Ubuntu desktop 20.04),
the initialization failed with the message (when running `SDL_GL_CreateContext(window)`)

  Error: Cannot create OpenGL Context! SDL Error: Invalid window

 gl_context = SDL_GL_CreateContext(window)